Front_end/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from back_end import db
from back_end import LoginForm, RegistrationForm, ContractorForm, ContChoiseForm, CustomerForm, OrderStatus
from back_end import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('start'))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('3D/d10_d11_login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            if form.order_role.data == 'customer':
                login_user(user)
                flash('Вы вошли на сайт как заказчик')
                return redirect(url_for('user.customer_cab'))
            elif form.order_role.data == 'contractor':
                login_user(user)
                flash('Вы вошли на сайт как исполнитель')
                return redirect(url_for('user.contractor_cab'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('start'))

@blueprint.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('start'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))
    flash('Пожалуйста, исправьте ошибки в форме')
    return redirect(url_for('user.register'))

@blueprint.route('/contractor_cab', methods=['GET','POST'])
def contractor_cab():
    title = "Кабинет исполнителя"
    ready = False # last value from DB
    contractor_form = ContractorForm()
    return render_template('3D/d9_contractor_cab.html', page_title=title, form=contractor_form)

@blueprint.route('/contractor_save', methods=['GET','POST'])
def contractor_save():
    form = ContractorForm()
    status_form = OrderStatus()
    if form.save.data:
        if form.validate_on_submit():
            if form.ready_for_order.data == 'yes':
                ready = True
                title = "Кабинет исполнителя"
                flash('Данные сохранены. Вы готовы принять заказ')
                return render_template('3D/d9_contractor_cab.html', page_title=title, form=form, ready=ready)
            elif form.ready_for_order.data == 'no':
                flash('Данные сохранены. Вы НЕ готовы принять заказ')
                ready = False
                title = "Кабинет исполнителя"
                return render_template('3D/d9_contractor_cab.html', page_title=title, form=form, ready=ready)
    elif form.new_order.data:
        title = "Новый заказ" 
        return render_template('3D/d12_new_order_accept.html', page_title=title)
    elif form.order.data:
        title = "Заказ №" 
        return render_template('3D/d13_order_in_process.html', page_title=title, form=status_form)   

@blueprint.route('/get_file', methods=['GET','POST'])
def get_file():
    with open('file.txt', 'w', encoding='utf-8') as new_file:
        new_file.write("3D Print MODEL")
    flash('Файл загружен')
    title = "Новый заказ" 
    # if current_user = contractor
    return render_template('3D/d12_new_order_accept.html', page_title=title)
    # elif current_user = customer
    # return render_template('3D/d5_order.html', page_title=title)

@blueprint.route('/get_file_order', methods=['GET','POST'])
def get_file_order():
    form = OrderStatus()
    with open('file.txt', 'w', encoding='utf-8') as new_file:
        new_file.write("3D Print MODEL")
    flash('Файл загружен')
    title = "Заказ №" 
    return render_template('3D/d13_order_in_process.html', page_title=title, form=form)

@blueprint.route('/order_accepted', methods=['GET','POST'])
def order_accepted():
    title = "Заказ принят" 
    return render_template('3D/d14_order_accepted.html', page_title=title)

@blueprint.route('/order_status', methods=['GET','POST'])
def order_status():
    form = OrderStatus()
    if form.no_done.data:
        title = "Заказ №" 
        flash('Статус заказа изменен на: НЕ ПОЛУЧИЛОСЬ СДЕЛАТЬ')
        return render_template('3D/d13_order_in_process.html', page_title=title, form=form)
    elif form.inwork.data:
        title = "Заказ №" 
        flash('Статус заказа изменен на: В РАБОТЕ')
        return render_template('3D/d13_order_in_process.html', page_title=title , form=form)
    elif form.done.data:
        title = "Заказ №" 
        flash('Статус заказа изменен на: ВЫПОЛНЕН')
        return render_template('3D/d13_order_in_process.html', page_title=title , form=form)

@blueprint.route('/customer_cab', methods=['GET','POST'])
def customer_cab():
    title = "Кабинет заказчика"
    form = CustomerForm()
    return render_template('3D/d2_customer_cab.html', page_title=title, form=form)

@blueprint.route('/my_order', methods=['GET','POST'])
def my_order():
    title = "Мой заказ №"
    form = CustomerForm()
    return render_template('3D/d5_order.html', page_title=title, form=form)

@blueprint.route('/new_order', methods=['GET','POST'])
def new_order():
    title = "Новый заказ"
    form = CustomerForm()
    return render_template('3D/d3_make_order.html', page_title=title, form=form)

@blueprint.route('/load_file', methods=['GET','POST'])
def load_file():
    #with open('file.txt', 'w', encoding='utf-8') as new_file:
     #   new_file.write("3D Print MODEL")
    form = CustomerForm()
    flash('Файл загружен')
    title = "Новый заказ" 
    return render_template('3D/d3_make_order.html', page_title=title, form=form)

@blueprint.route('/save_new_order', methods=['GET','POST'])
def save_new_order():
    title = "Заказ №"
    form = CustomerForm()
    choise_form = ContChoiseForm()
    if form.validate_on_submit():
        return render_template('3D/d4_new_order.html', page_title=title, form=choise_form)
    flash('Неверно заполнены данные')
    return redirect(url_for('user.new_order'))

@blueprint.route('/new_order_screen', methods=['GET','POST'])
def new_order_screen():
    title = "Заказ №"
    choise_form = ContChoiseForm()
    return render_template('3D/d4_new_order.html', page_title=title, form=choise_form)

@blueprint.route('/contractor_choise', methods=['GET','POST'])
def contractor_choise():
    title = "Кабинет заказчика"
    form = CustomerForm()
    return render_template('3D/d2_customer_cab.html', page_title=title, form=form)

Front_end/templates/base.html
<!doctype html>
    <html lang="ru">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
        <title>{{ page_title }}</title>
      </head>
      <body>

        <div class='container'>
            <h1>{{ page_title }}</h1>
            {% block content %}{% endblock %}
            
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      </body>
    </html>

Front_end/templates/d10_d11_login_old.html
{% extends "base.html" %}

{% block content %}

{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}

<form action="{{ url_for('user.process_login') }}" method="post">
    <br><br>
    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Введите адрес электронной почты</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
      </div>
    </div>
    <div class="form-group row">
      <label for="inputPassword3" class="col-sm-2 col-form-label">Введите пароль</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
      </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
      </div>
</form>
{% endblock %}  

Front_end/templates/d12_new_order_accept.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
<div class='row'>
        <div class='col-4'>
                <h2>Заказ 4 </h2>
        </div>
        <div class='col-8' align="right">
                <form action="{{ url_for('user.contractor_cab') }}" method="post">
                <button type="submit" class="btn btn-info">Назад к моим заказам</button>
                </form>
        </div>
</div>
<div class='row'>
    <div class='col-12'>
        <br>
    </div>
</div>
<div class='row'>
    <div class='col-6'>
            <div class="card" style="width: 18rem;">
                    <img src="https://ap-proekt.ru/upload/iblock/56f/56f6174c0cb0b368b2c6bf3c122b7e4d.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Заказ 1</h5>
                      <p class="card-text">Описание заказа и подробности по его производству.</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Заказчик</li>
                            <li class="list-group-item">Дата заказа</li>
                            <li class="list-group-item">Срок работы</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      
                    </div>
                  </div>
    </div>
    
    
</div>
<div class='row'>
        <div class='col-12'>
            <br>
        </div>
    </div>
<div class='row'>
        <div class='col-6'>
                <form action="{{ url_for('user.get_file') }}" method="post">
                        <button type="submit" class="btn btn-info btn-lg">Файл модели</button>
                </form>
        </div>
        <div class='col-3' align="right">
                <form action="{{ url_for('user.contractor_cab') }}" method="post">
                <button type="submit" class="btn btn-info btn-lg" style="background-color:rgb(250, 0, 71)">Отклонить</button>
                </form>
        </div>
        <div class='col-3' align="right">
                <form action="{{ url_for('user.order_accepted') }}" method="post">
                <button type="submit" class="btn btn-info btn-lg" style="background-color:rgb(60, 169, 71)">Принять</button>
                </form>
        </div>
</div>
{% endblock %}  

Front_end/templates/d13_order_in_process.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
<div class='row'>
        <div class='col-4'>
                <h2>Заказ 4 </h2>
        </div>
        <div class='col-8' align="right">
                <form action="{{ url_for('user.contractor_cab') }}" method="post">
                        <button type="submit" class="btn btn-info">Назад к моим заказам</button>
                </form>
        </div>
</div>
<div class='row'>
    <div class='col-12'>
        <br>
    </div>
</div>
<div class='row'>
    <div class='col-6'>
            <div class="card" style="width: 18rem;">
                    <img src="https://ap-proekt.ru/upload/iblock/56f/56f6174c0cb0b368b2c6bf3c122b7e4d.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Заказ 1</h5>
                      <p class="card-text">Описание заказа и подробности по его производству.</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Заказчик</li>
                            <li class="list-group-item">Дата заказа</li>
                            <li class="list-group-item">Срок работы</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      
                    </div>
                  </div>
    </div>
    
    
</div>
<div class='row'>
        <div class='col-12'>
            <br>
        </div>
    </div>
<div class='row'>
        <div class='col-7'>
                <form action="{{ url_for('user.get_file_order') }}" method="post">
                        <button type="submit" class="btn btn-info btn-lg">Файл модели</button>
                </form>
        </div>
        
                <form class="form-inline" action="{{ url_for('user.order_status') }}" method="post">
                <div class="col-5" align="left">
                        {{ form.no_done }}

                </div>
                <div class="col-4" align="center">
                        {{ form.inwork }}
                </div>
                <div class="col-3" align="right">
                        {{ form.done }}
                </div>

                </form>
                <br>
</div>
<br>
{% endblock %}  

Front_end/templates/d14_order_accepted.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
        <div class='col-12' align="center">
                <div class="alert alert-success" role="alert">
                        <h2>Заказ № успешно принят!</h2> <br>
                      </div>
                <br>  <br>  <br>  <br>  <br>
        </div>
        
</div>

<div class='row'>
        <div class='col-12' align="center">
                <br>  <br>  <br>  <br>  <br>
                <form action="{{ url_for('user.contractor_cab') }}" method="post">
                <button type="submit" class="btn btn-info btn-lg">Назад к моим заказам</button>
                </form>
        </div>
</div>
{% endblock %}  

Front_end/templates/d1_start.html
{% extends "base.html" %}

{% block content %}
    <h2 align="center" style="color: rgb(51, 88, 211);">Приветствуем Вас на нашем сайте!</h2>
    <div class='row'>
                <div class='col-6' align="center">
                    <form action="{{ url_for('user.login') }}" method="post">
                        <br>
                        <button type="submit" class="btn btn-primary btn-lg">Войти на сайт</button>
                    </form>
                </div>
                <div class='col-6' align="center">
                    <form action="{{ url_for('user.register') }}" method="post">
                        <br>
                        <button type="submit" class="btn btn-primary btn-lg">Зарегестрироваться</button>
                    </form>       
                </div>
    </div>
    
{% endblock %}  

Front_end/templates/d2_customer_cab.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
    <br>
<div class='row'>
        <div class='col-6'>
          <form action="{{ url_for('user.new_order') }}" method="post">
                <button type="submit" class="btn btn-info btn-lg">Добавить новую модель</button>
              </form>
        </div>
    <!--    <div class='col-6' align="right">
            <form action="{{ url_for('user.contractor_cab') }}" method="post">
              <button type="submit" class="btn btn-info">Назад к моим заказам</button>
              </form>
          </div> -->
</div>
<div class='row'>
    <div class='col-12'>
        <br>
    </div>
</div>
<div class='row'>
        <div class='col-12'>
                <h2>Мои заказы</h2> <br>
        </div>
    </div>
<div class='row'>
  <form class="form-inline" action="{{ url_for('user.my_order') }}" method="post">
    {{ form.hidden_tag() }}
    <div class='col-3'>    
            
                    <div class="form-group">
                                     {{form.order()}}
                    </div>
                  </div>
                </form>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://ap-proekt.ru/upload/iblock/56f/56f6174c0cb0b368b2c6bf3c122b7e4d.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Заказ 2</h5>
                      <p class="card-text">Описание заказа и подробности по его производству.</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Исполнитель</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Перейти к заказу</a>
                    </div>
                  </div>
    </div>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://ap-proekt.ru/upload/iblock/56f/56f6174c0cb0b368b2c6bf3c122b7e4d.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Заказ 3</h5>
                      <p class="card-text">Описание заказа и подробности по его производству.</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Исполнитель</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Перейти к заказу</a>
                    </div>
                  </div>
    </div>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://ap-proekt.ru/upload/iblock/56f/56f6174c0cb0b368b2c6bf3c122b7e4d.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Заказ 4</h5>
                      <p class="card-text">Описание заказа и подробности по его производству.</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Исполнитель</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Перейти к заказу</a>
                    </div>
                  </div>
    </div>
    
</div>
{% endblock %}  

Front_end/templates/d3_make_order.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}

    <br>
<div class='row'>
        <div class='col-3'>
                <form action="{{ url_for('user.load_file') }}" method="post">
                        <button type="submit" class="btn btn-info btn-lg">Загрузите модель</button>
                </form>
                <br>
        </div>
</div>
<div class='row'>
        <div class='col-12'>
            <br>
        </div>
    </div>
<div class='row'>
        <form action="{{ url_for('user.save_new_order') }}" method="post">
                {{ form.hidden_tag() }}
                <div class='col-12'>    
                        
                                <div class="form-group">
                                        <label> {{form.min_price.label()}} </label> <br>
                                        
                                                 {{form.min_price()}}
                                      </div>
                                <div class="form-group">
                                        <label> {{form.max_days.label()}} </label> <br>
                                        
                                                 {{form.max_days()}}
                                </div>
                                      
                                <div class="form-group">
                                        <label> {{form.adress.label()}} </label> <br>
                                        
                                        {{form.adress()}}
                                </div>
                  
                        {{ form.save }}
                <br>
                </div>
                </form>
                <br>
            <br>
            <br>
            <br>
            <br>
        </div>
</div>
{% endblock %}  

Front_end/templates/d4_new_order.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
<div class='row'>
        <div class='col-12' align="center">
                <div class="alert alert-success" role="alert">
                        Ваш заказ успешно создан - №4
                      </div>
                <br>  <br>  
        </div>
        
</div>
<div class='row'>
        <div class='col-12' align="center">
                <h2>Выберите подходящего исполнителя</h2> <br>
        </div>
    </div>
<div class='row'>
  <form class="form-inline" action="{{ url_for('user.contractor_choise') }}" method="post">
    {{ form.hidden_tag() }}
    <div class='col-3'>    
            
                    <div class="form-group">
                                     {{form.contractor()}}
                    </div>
                  </div>
                </form>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://a.d-cd.net/ec79a3es-1920.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Исполнитель 2</h5>
                      <p class="card-text">Краткая информация об исполнителе</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Срок</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Выбрать</a>
                    </div>
                  </div>
    </div>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://a.d-cd.net/ec79a3es-1920.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Исполнитель 3</h5>
                      <p class="card-text">Краткая информация об исполнителе</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Срок</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Выбрать</a>
                    </div>
                  </div>
    </div>
    <div class='col-3'>
            <div class="card" style="width: 18rem;">
                    <img src="https://a.d-cd.net/ec79a3es-1920.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Исполнитель 4</h5>
                      <p class="card-text">Краткая информация об исполнителе</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Срок</li>
                            <li class="list-group-item">Адрес</li>
                            <li class="list-group-item">Цена</li>
                          </ul>
                      <a href="#" class="btn btn-primary">Выбрать</a>
                    </div>
                  </div>
    </div>
    
</div>
<div class='row'>
        <div class='col-12' align="center">
                <br>  <br>  <br>  <br>  <br>
                <form action="{{ url_for('user.customer_cab') }}" method="post">
                  <button type="submit" class="btn btn-info btn-lg">Выбрать позже</button>
                </form>
                <br>
        </div>
</div>
<br>
{% endblock %}  

Front_end/templates/d9_contractor_cab.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
<div class='row'>
        <div class='col-12'>
                {% if ready %}
                <h2>Статус <span class="badge badge-success">Готов к заказам</span></h2>
                {% else %}
                <h2>Статус <span class="badge badge-danger">Не готов к заказам</span></h2>
                {% endif %}
        </div>
       
</div>
<div class='row'>
        <form action="{{ url_for('user.contractor_save') }}" method="post">
        {{ form.hidden_tag() }}
        <div class='col-12'>    
                
                        <div class="form-group">
                                <label> {{form.ready_for_order.label()}} </label> <br>
                                
                                         {{form.ready_for_order()}}
                                         
                        </div>
                        
                        <div class="form-group">
                                <label> {{form.min_price.label()}} </label> <br>
                                
                                         {{form.min_price()}}
                              </div>
                        <div class="form-group">
                                <label> {{form.min_days.label()}} </label> <br>
                                
                                         {{form.min_days()}}
                        </div>
                              
                        <div class="form-group">
                                <label> {{form.adress.label()}} </label> <br>
                                
                                {{form.adress()}}
                        </div>
          
                {{ form.save }}
        <br>
        </div>
        </form>
        <br>
</div>
<div class='row'>
        <form action="{{ url_for('user.contractor_save') }}" method="post">
        {{ form.hidden_tag() }}
        <div class='col-12'><br><br>
                <h2>Новые заказы</h2>      
                {{ form.new_order }}  <!-- не показывать, если отклонен этот заказ -->
                <h2>Принятые заказы</h2>      
                {{ form.order }}
        </div>
        </form>
        <br>
</div>       
{% endblock %}  

Front_end/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Главная страница </a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
          </form>
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">Привет, {{ current_user.username }}!</span>
                </li>
                {% if current_user.is_admin %}
                <li class="nav-item">
                    <a href="{{ url_for('admin.admin_index') }}" class="nav-link">Админка</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
                </li>
            {% endif %}
          </ul>         
        </div>
</nav>